#!/bin/zsh
#
# Copyright 2019-Present Erik Gomez.
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Only attempt to actively load the LaunchAgent if installing to a live system.
if [[ $3 == "/" ]] ; then
  LAUNCHD_LABEL="com.erikng.nudge"

  INSTALLER_USER=$(/usr/bin/stat -f '%Su' ${HOME})
  INSTALLER_USER_UID=$(/usr/bin/id -u ${INSTALLER_USER})
  echo "INSTALLER USER: ${INSTALLER_USER}"
  echo "UID: ${INSTALLER_USER_UID}"

  product_version=$(sw_vers -productVersion) # 10.14.6
  os_vers=( ${(@s:.:)product_version} )      # ( 10 14 6 )
  os_vers_major="${os_vers[1]}"              # 10
  os_vers_minor="${os_vers[2]}"              # 14
  os_vers_patch="${os_vers[3]}"              # 6
  os_vers_build=$(sw_vers -buildVersion)     # 18G103

  # If we're on OS X 10.10 or older
  if [[ "${os_vers_minor}" -le 10 ]]; then
    launchctl asuser ${INSTALLER_USER_UID} launchctl load -w "/Library/LaunchAgents/${LAUNCHD_LABEL}.plist"
  else
  # Assuming 10.11+
    # Is the LaunchAgent already installed?
    if launchctl blame gui/${INSTALLER_USER_UID}/$LAUNCHD_LABEL; then
      launchctl bootout gui/${INSTALLER_USER_UID}/$LAUNCHD_LABEL
    fi
    launchctl bootstrap gui/${INSTALLER_USER_UID} "/Library/LaunchAgents/${LAUNCHD_LABEL}.plist"
  fi
fi
